repos:
  - repo: local
    hooks:
      - id: scalafmt
        name: scalafmt
        language: system
        entry: sbt --no-colors scalafmtAll scalafmtSbt
        pass_filenames: false
        stages: [pre-commit]
