name: Continuous Integration

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]
    tags: [ 'v*' ]

jobs:
  test:
    name: Test Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Scala & Java
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17

      - name: Cache SBT & Coursier
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: sbt-${{ runner.os }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**') }}
          restore-keys: sbt-${{ runner.os }}-

      - name: Check Formatting
        run: sbt scalafmtCheckAll scalafmtSbtCheck

      - name: Compile & Test
        run: sbt clean compile test

  changelog:
    name: Generate Changelog
    runs-on: ubuntu-24.04
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: v${{ github.event.ref }}
          toTag: v${{ github.event.ref }}
          configurationJson: |
            {
              "template": "# Changelog\n\n{{CHANGELOG}}",
              "categories": [
                {"title": "✨ Features", "labels": ["feat", "feature"]},
                {"title": "🐛 Bug Fixes", "labels": ["fix", "bug"]},
                {"title": "📝 Documentation", "labels": ["docs"]},
                {"title": "⚡ Performance Improvements", "labels": ["perf"]},
                {"title": "♻️ Refactoring", "labels": ["refactor"]},
                {"title": "🧪 Tests", "labels": ["test"]},
                {"title": "🧹 Chores", "labels": ["chore"]},
                {"title": "📦 Dependencies", "labels": ["dependency"]},
                {"title": "🚨 Breaking Changes", "labels": ["breaking"]},
                {"title": "🤖 CI / Build", "labels": ["ci"]}
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|feature|fix|bug|perf|refactor|revert|style|test|dependency|breaking)(\\([\\w\\-\\.]+\\))?(!)?:",
                  "on_property": "title",
                  "target": "$1"
                },
                {
                  "pattern": "^(.*)!:.*",
                  "on_property": "title",
                  "target": "breaking"
                }
              ]
            }

  publish:
    name: Publish Release
    needs: [ test, changelog ]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Scala & Java
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17

      - name: Cache SBT & Coursier
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: sbt-${{ runner.os }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**') }}
          restore-keys: sbt-${{ runner.os }}-

      - name: Publish to Maven Central
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}